# Python is required for the deploy script
language: python
python:
- '3.6'

# The Sass part is the actual build
# or might be... eventually...
install:
- rvm install 2.4.1
# - gem install sass
- pip install -r .update/requirements.txt

script:
- echo "pip package versions:"
- pip freeze
- echo
- echo "Nothing to do, we're not actually compiling sass"

deploy:
# Updates on master go to /r/anime
- on:
    branch: master
  provider: script
  script: python .update/updateSubreddit.py anime
  skip_cleanup: true
# All other branches go to /r/animestaging for testing
- on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master
  provider: script
  script: python .update/updateSubreddit.py animestaging
  skip_cleanup: true
